baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "CMHAA"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
disableKinds = ["RSS"]

[taxonomies]
  category = "category"
  focus = "focus"
  role = "role"
  organisation_size = "organisation_size"
  industry = "industry"

[outputs]
home = ["HTML", "Algolia"]

[permalinks]
pages = "/:slug/"

[menu]
  [[menu.main]]
    identifier = "about-us"
    name = "About us"
    url = "/about-us/"
    weight = 1

  [[menu.main]]
    identifier = "our-stories"
    name = "Our Stories"
    url = "/our-stories/"
    weight = 2

  [[menu.main]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 3

# Algolia config
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "category"]
params = ["category"]
