backend:
  name: git-gateway
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "resources"
    label: "Resources"
    folder: "site/content/resources"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Banner Image",
          name: "banner_image",
          widget: "image",
          required: false,
        }
      - { label: "Banner Subcontent", name: "banner_subcontent", widget: markdown }
      - label: "Category"
        name: "category"
        widget: "select"
        options: 
          - { label: "Personal stories", value: 'personal-stories' }
          - { label: "Case studies", value: 'case-study' }
          - { label: "Fact sheets", value: 'fact-sheets' }
          - { label: "Guides & Toolkits", value: 'guides' }
          - { label: "Support services", value: 'support' }
          - { label: "Research", value: 'research' }
      - label: "Focus"
        name: "focus"
        widget: "select"
        options: 
          - { label: "Support for leaders, colleagues and staff", value: 'support' }
          - { label: "Assessment of organisational approach", value: 'assessment' }
          - { label: "Improving workplace culture", value: 'workplace-culture' }
          - { label: "Developing policy and practice", value: 'policy' }
      - label: "Role"
        name: "role"
        widget: "select"
        options: 
          - { label: "CEO or leadership", value: 'leadership' }
          - { label: "Senior manager", value: 'senior-manager' }
          - { label: "HR professional", value: 'hr-professional' }
          - { label: "Line manager/supervisor", value: 'line-manager' }
          - { label: "Sole trader", value: 'sole-trader' }
          - { label: "Employee", value: 'employee' }
          - { label: "Health or wellbeing lead", value: 'wellbeing-lead' }
          - { label: "Champion or advocate", value: 'champion' }
      - label: "Organisation size"
        name: "organisation_size"
        widget: "select"
        options: 
          - { label: "Micro (<10 employees)", value: "micro" }
          - { label: "Small (10-49 employees)", value: "small" }
          - { label: "Medium (50-249 employees)", value: "medium" }
          - { label: "Large (250+ employees)", value: "large" }
      - label: "Industry"
        name: "industry"
        widget: "select"
        options:
          - { label: "Retail & consumer", value: "retail" }
          - { label: "Manufacturing", value: "manufactoring" }
          - { label: "Property & Construction", value: "property" }
          - { label: "Transport & Logistics", value: "transport" }
          - { label: "Law & Legal Services", value: "legal" }
          - { label: "Financial & Insurance Services", value: "financial" }
          - { label: "Business Consulting & Management", value: "consulting" }
          - { label: "IT & Telecommunications", value: "it" }
          - { label: "Healthcare", value: "health" }
          - { label: "Recruitment & HR", value: "recruitment" }
          - { label: "Science & Pharmaceuticals", value: "science" }
          - { label: "Tourism & Hospitality", value: "tourism" }
          - { label: "Government & Public Agencies", value: "government" }
          - { label: "Education & Training", value: "education" }
          - { label: "Media, communications and digital", value: "media" }
          - { label: "Occupational health & rehabilitation", value: "occupational-health" }
          - { label: "Energy & Utilities", value: "energy" }
          - { label: "Charity, not-for-profit", value: "charity" }
          - { label: "Environment & agriculture", value: "environment" }
          - { label: "Emergency services & security", value: "emergency-services" }
      - { label: Content, name: content, widget: markdown }

  - name: "pages"
    label: "Pages"
    folder: "site/content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Banner Image",
          name: "banner_image",
          widget: "image",
          required: false,
        }
      - label: "Modules"
        name: "modules"
        widget: "list"
        types:
          - label: "Module 1"
            name: "module-1"
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
          - label: "Module 2"
            name: "module-2"
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subtitle, widget: string }
              - { label: Content, name: content, widget: markdown }
