backend:
  name: git-gateway
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "resources"
    label: "Resources"
    folder: "site/content/resources"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Banner Image", name: "banner_image", widget: "image", required: false }
      - { label: "Banner Subcontent", name: "banner_subcontent", widget: markdown, required: false }
      - label: "Category"
        name: "category"
        widget: "select"
        options: [
          "Personal stories",
          "Case studies",
          "Fact sheets",
          "Guides & Toolkits",
          "Support services",
          "Research"
        ]
      - label: "Focus"
        name: "focus"
        widget: "select"
        options: [
          "Support for leaders, colleagues and staff",
          "Assessment of organisational approach",
          "Improving workplace culture",
          "Developing policy and practice"
        ]
      - label: "Role"
        name: "role"
        widget: "select"
        options: [
          "CEO or leadership",
          "Senior manager",
          "HR professional",
          "Line manager/supervisor",
          "Sole trader",
          "Employee",
          "Health or wellbeing lead",
          "Champion or advocate"
        ]
      - label: "Organisation size"
        name: "organisation_size"
        widget: "select"
        options: [
          "Micro (<10 employees)",
          "Small (10-49 employees)",
          "Medium (50-249 employees)",
          "Large (250+ employees)"
        ]
      - label: "Industry"
        name: "industry"
        widget: "select"
        options: [
          "Retail & consumer",
          "Manufacturing",
          "Property & Construction",
          "Transport & Logistics",
          "Law & Legal Services",
          "Financial & Insurance Services",
          "Business Consulting & Management",
          "IT & Telecommunications",
          "Healthcare",
          "Recruitment & HR",
          "Science & Pharmaceuticals",
          "Tourism & Hospitality",
          "Government & Public Agencies",
          "Education & Training",
          "Media, communications and digital",
          "Occupational health & rehabilitation",
          "Energy & Utilities",
          "Charity, not-for-profit",
          "Environment & agriculture",
          "Emergency services & security"
        ]
      - { label: Content, name: content, widget: markdown, required: false }

  - name: "pages"
    label: "Pages"
    folder: "site/content"
    create: true
    fields:
      - { label: "Page Title", name: "page_title", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Banner Image", name: "banner_image", widget: "image", required: false }
      - { label: "Banner CTA Link", name: "banner_cta_link", widget: "string", required: false }
      - { label: "Banner CTA Text", name: "banner_cta_text", widget: "string", required: false }
      - label: "Modules"
        name: "modules"
        widget: "list"
        types:
          - label: "Accordion"
            name: "accordion"
            widget: object
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: "Our Members"
            name: "our_members"
            widget: "list"
            fields:
              - {label: Title, name: our_members_title, widget: string, default: "Our Members", required: true}
              - {label: Description, name: our_members_description, widget: markdown, default: "Description goes here"}
              - label: Member
                name: member
                widget: list
                allow_add: true
                fields:
                  - {label: Our Member Image, name: our_member_image, widget: image}
                  - {label: Our Member Link, name: our_member_link, widget: string}
          - label: "Split Title with Content"
            name: "split_title_content"
            widget: object
            fields:
              - { label: Title, name: title, widget: string, required: true }
              - { label: Lead Text, name: leadtext, widget: string, required: true }
              - { label: Content, name: content, widget: markdown, required: true }
          - label: "Spotlight with Image & Content"
            name: "spotlight_image_content"
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Title 1, name: title1, widget: string, required: true }
              - { label: Content 1, name: content1, widget: markdown, required: true }
              - { label: Title 2, name: title2, widget: string }
              - { label: Content 2, name: content2, widget: markdown }
          - label: "Statistics"
            name: "statistics"
            widget: object
            fields:
              - { label: Statistic Number 1, name: stat_number_1, widget: number, valueType: "float" }
              - { label: Statistic Type 1, name: stat_type_1, widget: string }
              - { label: Info 1, name: stat_info_1, widget: markdown }
              - { label: Statistic Number 2, name: stat_number_2, widget: number, valueType: "float" }
              - { label: Statistic Type 2, name: stat_type_2, widget: string }
              - { label: Info 2, name: stat_info_2, widget: markdown }
              - { label: Statistic Number 3, name: stat_number_3, widget: number, valueType: "float" }
              - { label: Statistic Type 3, name: stat_type_3, widget: string }
              - { label: Info 3, name: stat_info_3, widget: markdown }
          - label: "Pillar Content - Card, Image & Description"
            name: "pillar-content-cards"
            widget: object
            fields:
              - { label: Intro Title, name: intro_title, widget: string, required: true }
              - { label: Intro Description, name: intro_description, widget: markdown, required: true }
              - { label: Card Image 1, name: card_image_1, widget: image, required: true }
              - { label: Card Title 1, name: card_title_1, widget: string, required: true }
              - { label: Card Description 1, name: card_description_1, widget: markdown, required: true }
              - { label: Card Image 2, name: card_image_2, widget: image }
              - { label: Card Title 2, name: card_title_2, widget: string }
              - { label: Card Description 2, name: card_description_2, widget: markdown }
              - { label: Card Image 3, name: card_image_3, widget: image }
              - { label: Card Title 3, name: card_title_3, widget: string }
              - { label: Card Description 3, name: card_description_3, widget: markdown }
          - label: "Call Out with Image, text & CTA"
            name: "callout-image-text-cta"
            widget: object
            fields:
              - { label: Call Out Image, name: callout_image, widget: image, required: true }
              - { label: Call Out Title, name: callout_title, widget: string, required: true }
              - { label: Call Out Description, name: callout_description, widget: markdown, required: true }
              - { label: Call Out CTA Link, name: callout_cta_link, widget: string }
              - { label: Call Out CTA Text, name: callout_cta_text, widget: string }
          - label: "Stacked Content with Top Image"
            name: "stacked-content-top-image"
            widget: object
            fields:
              - { label: Stacked Image, name: stacked_image, widget: image }
              - { label: Stacked Title, name: stacked_title, widget: string, required: true }
              - { label: Stacked Description, name: stacked_description, widget: markdown, required: true }
              - { label: Stacked CTA Link, name: stacked_cta_link, widget: string }
              - { label: Stacked CTA Text, name: stacked_cta_text, widget: string }
          - label: "Feature Member Stories"
            name: "feature-member-stories"
            widget: "list"
            fields:
              - {label: Intro, name: feat_member_intro, widget: string, default: "Hear from some of our members and get to know their story.", required: true}
              - label: Feature Member
                name: feat_member
                widget: list
                allow_add: true
                fields:
                  - {label: Feature Member Image, name: feat_member_image, widget: image}
                  - {label: Feature Member Description, name: feat_member_description, widget: string}
                  - {label: Feature Member Link, name: feat_member_link, widget: string}
                  - {label: Feature Member CTA Text, name: feat_member_cta, widget: string}
              - {label: Read more stories link, name: feat_member_read_more, widget: string}
